AWSTemplateFormatVersion: '2010-09-09'

Resources:
  LambdaCodeBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'lambda-code-bucket-exercise'

Outputs:
  BucketNameOutput:
    Description: "Nombre del S3 Bucket"
    Value: !Ref LambdaCodeBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"