name: Deploy Lambda and API Gateway

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y unzip > /dev/null
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null
          unzip awscliv2.zip > /dev/null
          sudo ./aws/install --update > /dev/null 2>&1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::337918032209:role/GithubRoleOIDC
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack - S3 bucket
        run: |
             aws cloudformation deploy \
              --template-file bucket_template.yml \
              --stack-name S3BucketStack \
              --capabilities CAPABILITY_IAM

      - name: Zip Lambda function - Example
        run: |
             cd s3_example_file
             zip -r example.zip example.py requirements.txt

      - name: Upload Lambda code to S3
        run: |
             aws s3 cp s3_example_file/example.zip s3://lambda-code-bucket-exercise/lambda/example.zip

      - name: Deploy CloudFormation Stack - Lambda - API Gateway
        run: |
             aws cloudformation deploy \
                --template-file lambda_template.yml \
                --stack-name ApplicationStack \
                --capabilities CAPABILITY_IAM